theme:
  name: 'material'
  custom_dir: overrides
  palette:
    scheme: slate
    primary: blue
    accent: blue
  font:
    text: Noto Sans
    code: Fira Mono
  language: pl
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - navigation.expand
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - content.code.copy
  logo: assets/icon.svg
  favicon: assets/icon.png
site_name: Unoverse Networks
site_url: "https://networks.unoverse.pl"
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list 
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.tabbed:
      alternate_style: true 
plugins:
  - search
  - glightbox
extra:
  social:
    - icon: zst/zst
      link: https://zst-tarnow.pl
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/zst_tarnow/
    - icon: unoverse/unoverse
      link: https://madanowicz.pl
copyright: "Autor: Marcin Madanowicz - ZST Tarnów"
nav:
  - 'index.md'
  - MikroTik Routerboard:
    - "mikrotik/konfiguracja-wstepna.md"
    - "mikrotik/ip.md"
    - "mikrotik/dhcp.md"
    - "mikrotik/port-forwarding.md"
    - "mikrotik/vlan-podstawy.md"
